use [DB_994D7D_DbTree]
drop table [dbo].[AppConfig]
drop table [dbo].[BetItem]
drop table [dbo].[Bet]
drop table [dbo].[PKLog]
drop table [dbo].[PKRate]
drop table [dbo].[PKBonus]
drop table [dbo].[PK]
drop table [dbo].[Post]
drop table [dbo].[Rate]
drop table [dbo].[UserExtend]
drop table [dbo].[UserRole]
drop table [dbo].[User]
drop table [dbo].[Role]