
drop table [dbo].[AppConfig]
drop table [dbo].[PKLog]
drop table [dbo].[LoginLog]
drop table [dbo].[PKRate]
drop table [dbo].[PKBonus]
drop table [dbo].[BetItem]
drop table [dbo].[Bet]
drop table [dbo].[PK]
drop table [dbo].[Post]
drop table [dbo].[Rate]
drop table [dbo].[UserExtension]
drop table [dbo].[UserRebate]
drop table [dbo].[UserRole]
drop table [dbo].[User]
drop table [dbo].[MenuRole]
drop table [dbo].[Role]
drop table [dbo].[Menu]